-- =============================================================================
-- Governance 01 - Tags & demo roles
-- Tag once -> policies follow the data everywhere (marts, semantic view, apps).
-- Idempotent. Run as ACCOUNTADMIN.
-- =============================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE CROCEVIA_DB;

-- --- Demo roles -------------------------------------------------------------
-- Steward sees everything; store manager is the "governed" persona used to prove
-- masking + row-access live.
CREATE ROLE IF NOT EXISTS CROCEVIA_DATA_STEWARD;
CREATE ROLE IF NOT EXISTS CROCEVIA_STORE_MANAGER_DEMO;

GRANT USAGE ON DATABASE CROCEVIA_DB TO ROLE CROCEVIA_DATA_STEWARD;
GRANT USAGE ON DATABASE CROCEVIA_DB TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
GRANT USAGE ON SCHEMA CROCEVIA_DB.PLATFORM_DEMO TO ROLE CROCEVIA_DATA_STEWARD;
GRANT USAGE ON SCHEMA CROCEVIA_DB.PLATFORM_DEMO TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
GRANT USAGE ON WAREHOUSE CR_DEV_WH TO ROLE CROCEVIA_DATA_STEWARD;
GRANT USAGE ON WAREHOUSE CR_DEV_WH TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
GRANT SELECT ON ALL TABLES IN SCHEMA CROCEVIA_DB.PLATFORM_DEMO TO ROLE CROCEVIA_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA CROCEVIA_DB.PLATFORM_DEMO TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CROCEVIA_DB.PLATFORM_DEMO TO ROLE CROCEVIA_DATA_STEWARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CROCEVIA_DB.PLATFORM_DEMO TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
-- Store manager also reads the CRM base table to make masking visible
GRANT USAGE ON SCHEMA CROCEVIA_DB.BRONZE_DATA TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
GRANT SELECT ON TABLE CROCEVIA_DB.BRONZE_DATA.CROCEVIA_CRM TO ROLE CROCEVIA_STORE_MANAGER_DEMO;
GRANT USAGE ON SCHEMA CROCEVIA_DB.BRONZE_DATA TO ROLE CROCEVIA_DATA_STEWARD;
GRANT SELECT ON TABLE CROCEVIA_DB.BRONZE_DATA.CROCEVIA_CRM TO ROLE CROCEVIA_DATA_STEWARD;
-- Let the current user assume the personas during the demo
GRANT ROLE CROCEVIA_DATA_STEWARD TO ROLE ACCOUNTADMIN;
GRANT ROLE CROCEVIA_STORE_MANAGER_DEMO TO ROLE ACCOUNTADMIN;

-- --- Tag taxonomy -----------------------------------------------------------
USE SCHEMA CROCEVIA_DB.PLATFORM_DEMO;

CREATE TAG IF NOT EXISTS SENSITIVITY
  ALLOWED_VALUES 'PII', 'CONFIDENTIAL', 'PUBLIC'
  COMMENT = 'Data sensitivity classification';

CREATE TAG IF NOT EXISTS DATA_DOMAIN
  ALLOWED_VALUES 'SALES', 'CUSTOMER', 'PRODUCT', 'STORE', 'FINOPS'
  COMMENT = 'Business data domain (for catalog / domain onboarding)';

CREATE TAG IF NOT EXISTS COST_CENTER
  ALLOWED_VALUES 'DATA_PLATFORM', 'MARKETING', 'SUPPLY_CHAIN', 'FINANCE'
  COMMENT = 'Cost-center for FinOps chargeback';

CREATE TAG IF NOT EXISTS ENVIRONMENT
  ALLOWED_VALUES 'PRD', 'REC', 'DEV'
  COMMENT = 'Deployment environment';

-- --- Apply object-level tags -----------------------------------------------
ALTER WAREHOUSE CR_DEV_WH SET TAG CROCEVIA_DB.PLATFORM_DEMO.COST_CENTER = 'DATA_PLATFORM';
ALTER SCHEMA CROCEVIA_DB.PLATFORM_DEMO SET TAG CROCEVIA_DB.PLATFORM_DEMO.DATA_DOMAIN = 'SALES';
ALTER SCHEMA CROCEVIA_DB.PLATFORM_DEMO SET TAG CROCEVIA_DB.PLATFORM_DEMO.ENVIRONMENT = 'DEV';

-- --- Apply PII tags to CRM columns (drives tag-based masking in 02) ---------
ALTER TABLE CROCEVIA_DB.BRONZE_DATA.CROCEVIA_CRM MODIFY COLUMN EMAIL      SET TAG CROCEVIA_DB.PLATFORM_DEMO.SENSITIVITY = 'PII';
ALTER TABLE CROCEVIA_DB.BRONZE_DATA.CROCEVIA_CRM MODIFY COLUMN PHONE      SET TAG CROCEVIA_DB.PLATFORM_DEMO.SENSITIVITY = 'PII';
ALTER TABLE CROCEVIA_DB.BRONZE_DATA.CROCEVIA_CRM MODIFY COLUMN FIRST_NAME SET TAG CROCEVIA_DB.PLATFORM_DEMO.SENSITIVITY = 'PII';
ALTER TABLE CROCEVIA_DB.BRONZE_DATA.CROCEVIA_CRM MODIFY COLUMN LAST_NAME  SET TAG CROCEVIA_DB.PLATFORM_DEMO.SENSITIVITY = 'PII';

SHOW TAGS IN SCHEMA CROCEVIA_DB.PLATFORM_DEMO;
